Кеширование + контроль версий
maxibello/skillbox pull request #16
Opened 2020-08-22 10:33 UTC by maxibello

2020-08-24 15:16 UTC, ios-review requested changes
Все работает согласно требованиям.
Гуд!

По коду еще поработаем?

2020-08-24 15:16 UTC, ios-review commented on skillbox_12.1/skillbox_12.1/DBManager.swift
> +class DBManager {
DBManager очень отстраненное название.
Более понятное было бы CharacterDB.
Рекомендую к изучению swift api design guidelines https://swift.org/documentation/api-design-guidelines/

2020-08-24 15:16 UTC, ios-review commented on skillbox_12.1/skillbox_12.1/Model/Character.swift
> +            try image.pngData()?.write(to: filePath, options: .atomic)
Если выполнять данный код на главном потоке, то можно "залагать" ui.

2020-08-24 15:16 UTC, ios-review commented on skillbox_12.1/skillbox_12.1/Controller/CharacterDetailVC.swift
> +        DBManager.sharedInstance.edit(object: character) {
В общем случае может быть довольно дорогой операцией по производительности, что может "затормозить" ui.

2020-08-24 15:16 UTC, ios-review commented on skillbox_12.1/skillbox_12.1/Controller/CharactersViewController.swift
> +        characters = Array(realmStorage.getDataFromDB())
Может быть очень длительная по времени операция.
UI "залипнет", что отрицательно скажется на пользовательском опыте.

2020-08-24 15:16 UTC, ios-review commented on skillbox_12.1/skillbox_12.1/Controller/CharactersViewController.swift
> +                        if let receivedObject = self.receivedObjects.first(where: { $0.id == modifiedObject.id }) {
if contains
+
if let first
по смыслу абсолютно идентичны
Если `if let receivedObject = self.receivedObjects.first(where: { $0.id == modifiedObject.id })` вернет результат, то contains тоже будет true.
Кажется, что первое условие избыточно.

2020-08-24 15:16 UTC, ios-review commented on skillbox_12.1/skillbox_12.1/Controller/CharactersViewController.swift
> +                        if let receivedObject = self.receivedObjects.first(where: { $0.id == modifiedObject.id }) {
`let conflictedObjects = self.receivedObjects.filter { r in modifiedObjects.contains { r.id == $0.id } }`

2020-08-25 09:16 UTC, maxibello commented on skillbox_12.1/skillbox_12.1/Controller/ConflictResolverVC.swift
> +class ConflictResolverVC: UIViewController {
done

2020-08-25 09:16 UTC, maxibello commented on skillbox_12.1/skillbox_12.1/Controller/CharacterDetailVC.swift
> +class CharacterDetailVC: UIViewController {
done

2020-08-25 09:17 UTC, maxibello commented on skillbox_12.1/skillbox_12.1/DBManager.swift
> +class DBManager {
done

2020-08-25 19:41 UTC, maxibello commented on skillbox_12.1/skillbox_12.1/DBManager.swift
> +class DBManager {
done

2020-08-25 20:51 UTC, maxibello commented on skillbox_12.1/skillbox_12.1/Controller/CharactersViewController.swift
> +                        if let receivedObject = self.receivedObjects.first(where: { $0.id == modifiedObject.id }) {
упростил

2020-08-25 21:03 UTC, maxibello commented on skillbox_12.1/skillbox_12.1/Controller/CharactersViewController.swift
> +        collectionView.refreshControl = UIRefreshControl()
done

2020-08-26 07:02 UTC, maxibello commented on skillbox_12.1/skillbox_12.1/Model/Character.swift
> +            try image.pngData()?.write(to: filePath, options: .atomic)
поправил

2020-08-26 15:20 UTC, maxibello commented on skillbox_12.1/skillbox_12.1/Controller/CharacterDetailVC.swift
> +        DBManager.sharedInstance.edit(object: character) {
done

2020-08-26 16:22 UTC, maxibello commented on skillbox_12.1/skillbox_12.1/Controller/CharactersViewController.swift
> +        characters = Array(realmStorage.getDataFromDB())
Все попытки получать данные в другом thread закончились неудачей (пробовал по аналогии с записью через ThreadSafeReference). Краш из-за попытки обращения к realm из другого thread.

2020-08-27 12:09 UTC, ios-review approved these changes
Все экраны имеют хороший layout и хорошо отрисовываются для iPhone SE (2nd) и больших экранах.
Приложение работает быстро! Очень удобно пользоваться!
Реквест можно мержить.

Экран разрешения конфликтов немного не влезает на SE (2nd).
![image](https://user-images.githubusercontent.com/62285448/91440452-d2f27700-e898-11ea-8a81-372383503141.png)

2020-08-27 12:09 UTC, ios-review commented on skillbox_12.1/skillbox_12.1/Controller/CharactersViewController.swift
> +        characters = Array(realmStorage.getDataFromDB())
По ссылке https://realm.io/docs/swift/latest/#threading вы сможете ознакомиться с АПИ для работы в разных потоках.

Объект базы (Realm) должен использовать в потоке, где был создан, так же как и объекты модели.

Объекты модели CoreData тоже должны быть использованы в потоке, в котором были созданы.
Зато сам NSManagedObjectContext может использоваться из любого потока.

2020-09-08 09:08 UTC, merged