Reactive
maxibello/skillbox pull request #22
Opened 2020-09-17 09:48 UTC by maxibello

2020-09-19 05:08 UTC, ios-review requested changes
На высоте🧗🏻

Усложняем)

2020-09-19 05:08 UTC, ios-review commented on s02e03_Reactive/s02e03_Reactive/d/LabelButtonVC.swift
> +            self.counterLabel.text = "\((Int(self.counterLabel.text ?? "") ?? 0) + 1)"
Много каст операций.
Может быть хранить текущее значение в виде Int, а затем его преобразовывать?

Дополнительно:
1. Добавить декремент.
2. Представим, что инкремент/декремент длятся некоторое продолжительное время (0.5 секунд или больше).
3. При этом позволяем пользователю нажимать произвольно + и - без блокирования и отображения индикатора ожидания.
4. Создать последовательную очередь выполнения операций.
5. Отобразить эту очередь где-нибудь внизу на экране. Дебаг-фича.

Процесс такой:
1. Пользователь нажал +. Операция +1 добавилась в очередь и отобразилась внизу.
2. Пользователь нажал +. Операция +1 добавилась в очередь и отобразилась внизу.
3. Пользователь нажал -. Операция -1 добавилась в очередь и отобразилась внизу.
**Результат:** Сейчас в очереди три операции ++-
4. Прошло 0.5 сек с первой операции. Изменилось значение лейбла на +1. Операция +1 удалилась из очереди внизу.
5. Прошло 0.5 сек с второй операции. Изменилось значение лейбла на +1. Операция +1 удалилась из очереди внизу.
6. Прошло 0.5 сек с третей операции. Изменилось значение лейбла на -1. Операция -1 удалилась из очереди внизу.
**Результат:** очередь пуста, значение лейбла +2.

2020-09-19 05:08 UTC, ios-review commented on s02e03_Reactive/s02e03_Reactive/e/RocketVC.swift
> +          .disposed(by: disposeBag)
Можно ли сделать так, чтобы после того, как ракета запущена, больше данные потоки не запускались?

2020-09-21 15:06 UTC, maxibello commented on s02e03_Reactive/s02e03_Reactive/a/TextFieldVC.swift
> +            .disposed(by: disposeBag)
добавил observable на `.editingDidEnd`

2020-09-21 15:06 UTC, maxibello commented on s02e03_Reactive/s02e03_Reactive/c/TableVC.swift
> +                    self.items.onNext(newItems)
done

2020-09-21 15:29 UTC, maxibello commented on s02e03_Reactive/s02e03_Reactive/c/TableVC.swift
> +class TableVC: UIViewController {
done

2020-09-21 16:00 UTC, maxibello commented on s02e03_Reactive/s02e03_Reactive/e/RocketVC.swift
> +          .disposed(by: disposeBag)
done

2020-09-22 09:39 UTC, maxibello commented on s02e03_Reactive/s02e03_Reactive/d/LabelButtonVC.swift
> +            self.counterLabel.text = "\((Int(self.counterLabel.text ?? "") ?? 0) + 1)"
done

2020-09-23 12:30 UTC, ios-review reviewed
+++

Мержим

2020-09-23 12:30 UTC, ios-review commented on s02e03_Reactive/s02e03_Reactive/b/DelayedRequestVC.swift
> +                DispatchQueue.main.asyncAfter(deadline: .now() + 1, execute: {
work item можно было передать в качестве параметра.

2020-09-23 12:30 UTC, ios-review commented on s02e03_Reactive/s02e03_Reactive/b/DelayedRequestVC.swift
> +                DispatchQueue.main.asyncAfter(deadline: .now() + 1, execute: {
https://developer.apple.com/documentation/dispatch/dispatchqueue/2300020-asyncafter

2020-09-23 12:30 UTC, ios-review commented on s02e03_Reactive/s02e03_Reactive/b/DelayedRequestVC.swift
> +    }
А почему именно здесь, а не во viewDidLoad?

2020-09-23 12:31 UTC, ios-review approved these changes

2020-09-23 13:21 UTC, maxibello commented on s02e03_Reactive/s02e03_Reactive/b/DelayedRequestVC.swift
> +    }
на стеке было написано, что ворнинг вызван как раз байндом во viewDidLoad :)

2020-09-23 13:21 UTC, merged