S02e04 architecture
maxibello/skillbox pull request #23
Opened 2020-09-28 08:18 UTC by maxibello

2020-09-29 08:08 UTC, ios-review requested changes
Очень скоро вы будете писать в прод и будете делать это клево!

Во всех приложениях есть ошибка layout при открытии первого экрана.
<img width="1399" alt="Screenshot 2020-09-29 at 14 19 05" src="https://user-images.githubusercontent.com/62285448/94530566-769ec080-0265-11eb-995f-913ca2c44d12.png">

+ немного доработать реализации архитектур.

2020-09-29 08:08 UTC, ios-review commented on s02e04_mvvm/s02e04_mvvm/ViewModel/CategoriesViewModel.swift
> +        BlackStarApiService.loadCategories() { [weak self] result in
Получится ли написать unit-тест на данную вью модель?

Если да, то реализуйте.
Если нет, то почему?
Как можно поправить реализацию, чтобы написание теста стало возможным?
Поправьте и напишите unit-тест на эту вью модель.

2020-09-29 08:08 UTC, ios-review commented on s02e04_viper/s02e04_viper/CategoryModule/CategoryPresenter.swift
> +    var interactor: CategoryIteractorInput? { get set }
Обычно interactor является приватной зависимостью презентера.

Протоколы Input/Output содержат только свойства и методы, связанные с задачей презентера, с его логикой.

2020-09-29 08:08 UTC, ios-review commented on s02e04_viper/s02e04_viper/ToDoListModule/ToDoListInteractor.swift
> +class ToDoListInteractor: ToDoListInteractorInput {
unit-тест, пожалуйста)

2020-09-29 08:08 UTC, ios-review commented on s02e04_viper/s02e04_viper/CategoryModule/CategoryIteractor.swift
> +        BlackStarApiService.loadCategories() { [weak self] result in
И здесь unit-тест.

2020-09-29 08:08 UTC, ios-review commented on s02e04_viper/s02e04_viper/ToDoListModule/ToDoListViewController.swift
> +        present(alert, animated: true, completion: nil)
Презентовать новый viewcontroller, то есть новый модуль, в viper принято с помощью router.

Реализуйте router в архитектуре viper и используйте его для презентации новых экранов.

2020-09-29 08:08 UTC, ios-review commented on s02e04_viper/s02e04_viper/Extension/ViewController+showError.swift
> +        self.present(alertController, animated: true, completion: nil)
viper: r - router.

2020-09-30 14:48 UTC, maxibello commented on BlackStar/BlackStar/Controller/CategoryVC.swift
> -    let basketHelper = BasketControlHelper()
copy-paste с диломного проекта, не дочистил

2020-09-30 14:48 UTC, maxibello commented on s02e04_mvc/s02e04_mvc/Controller/CategoryVC.swift
> +class CategoryVC: UITableViewController {
ага, для MVVM пришлось разделять

2020-09-30 15:29 UTC, maxibello commented on BlackStar/BlackStar/Controller/CategoryVC.swift
> -    let basketHelper = BasketControlHelper()
проект мой если что) лежит в репе (BlackStar)

2020-09-30 15:37 UTC, maxibello commented on s02e04_mvc/s02e04_mvc/Controller/CategoryVC.swift
> +                    .filter { $0.subcategories!.count > 0 }
упадет, в production коде вообще не должно быть ! (есть некоторые исключения типа outlets), убрал

2020-10-03 12:55 UTC, maxibello commented on s02e04_mvc/s02e04_mvc/Controller/CategoryVC.swift
> +    }
done

2020-10-03 12:55 UTC, maxibello commented on s02e04_mvc/s02e04_mvc/Controller/CategoryVC.swift
> +    }()
done

2020-10-03 20:46 UTC, maxibello commented on s02e04_viper/s02e04_viper/CategoryModule/CategoryPresenter.swift
> +    var interactor: CategoryIteractorInput? { get set }
done

2020-10-03 20:46 UTC, maxibello commented on s02e04_viper/s02e04_viper/ToDoListModule/ToDoListInteractor.swift
> +class ToDoListInteractor: ToDoListInteractorInput {
done

2020-10-03 20:46 UTC, maxibello commented on s02e04_viper/s02e04_viper/CategoryModule/CategoryIteractor.swift
> +        BlackStarApiService.loadCategories() { [weak self] result in
done

2020-10-03 20:46 UTC, maxibello commented on s02e04_viper/s02e04_viper/ToDoListModule/ToDoListViewController.swift
> +        present(alert, animated: true, completion: nil)
done

2020-10-04 12:54 UTC, ios-review requested changes
По тестам не уловил мысли.

Еще раз повторим?)

2020-10-04 12:54 UTC, ios-review commented on s02e04_mvc/s02e04_mvc/Controller/CategoryVC.swift
> +}
Красивый класс стал)

Еще можно ограничить доступ к свойствам этой рут вью и предоставить только методы для изменения состояния вью.
И только через этот интерфейс общаться со слоем вью.

2020-10-04 12:54 UTC, ios-review commented on s02e04_mvvm/s02e04_mvvm/ViewModel/CategoriesViewModel.swift
> +        BlackStarApiService.loadCategories() { [weak self] result in
Тестов на вью модель так и не увидел(

2020-10-04 12:54 UTC, ios-review commented on s02e04_viper/s02e04_viper/CategoryModule/CategoryRouter.swift
> +class CategoryRouter: CategoryRouterInput {
👍

2020-10-04 12:54 UTC, ios-review commented on s02e04_viper/s02e04_viper/ToDoListModule/ToDoListConfigurator.swift
> +class TDLConfigurator: TDLConfiguratorProtocol {
конфигуратор 👌

Вы в небольшом шаге до DI контейнеров!

2020-10-04 12:54 UTC, ios-review commented on s02e04_viper/s02e04_viperTests/CategoryInteractorTests.swift
> +    }
Какой реальный код на продакшне теструет этот код?
Мне кажется, этот код тестирует только MockInteractor, который никак не связан с кодом приложения.

Unit-тест на класс пишутся с учетом того, что используется конкретный тестируемый класс из приложения, а все его зависимости мокаются.
В данном случае это тест на реализацию MockInteractor, которая никак не связана с приложением.

Зачем тестировать то, что не используется кодом приложения?

2020-10-04 12:54 UTC, ios-review commented on s02e04_viper/s02e04_viperTests/CategoryInteractorTests.swift
> +    }
Попробуете еще раз?

2020-10-04 12:54 UTC, ios-review commented on s02e04_viper/s02e04_viperTests/CategoryInteractorTests.swift
> +    }
Если есть вопросы, то буду рад ответить на них.

2020-10-04 16:29 UTC, maxibello commented on s02e04_viper/s02e04_viperTests/CategoryInteractorTests.swift
> +    }
Да, есть вопрос по тестированию метода загрузки категорий по HTTP.
Метод `.fetchCategories()` асинхронный, из-за этого assert падает как я понимаю. В XCTest есть механизм expectations, но для этого нужен доступ к коллбеку загрузки данных. То есть получается мне нужно для теста делать какой-то дополнительный метод? Либо я могу протестировать только сервис загрузки данных. Даже если замокировать ответ, все равно assert падает.

2020-10-05 13:55 UTC, ios-review requested changes
Добавил ответ на вопрос.

2020-10-05 13:55 UTC, ios-review commented on s02e04_viper/s02e04_viper/CategoryModule/CategoryInteractor.swift
> +    }
О завершении fetchCategories можно узнать с помощью outputDelegate в двух методах: categoriesDidReceived и categoriesReceiveError.
Если они вызвались, то fetchCategories завершился.
Именно в реализации CategoryInteractorOutput можно изменять expectation.
Эту реализацию можно легко подменить.
Плюс такое поведение полностью соответствует контракту класса.

Но как проверить, что fetchCategories возвращает именно правильные данные?
Как узнать, что грузятся они с того места, где нужно?
Вдруг внутри fetchCategories в настоящей реализации используется другой метод, отличный от BlackStarApiService.loadCategories().
Или вдруг кто-то перепишет и будет брать категории из другого метода, который не будет удовлетворять нашим требованиям?

Для таких случаев используются моки.
Какие существуют способы в данном случае замокировать BlackStarApiService?

2020-10-05 15:00 UTC, maxibello commented on s02e04_viper/s02e04_viper/CategoryModule/CategoryInteractor.swift
> +    }
Ок, я почему-то не догадался пробросить expectation в outputDelegate...Мокирую я с помощью Mockingjay

2020-10-06 13:16 UTC, ios-review approved these changes
🔥

merge

2020-10-06 16:50 UTC, merged