Concurrency
maxibello/skillbox pull request #24
Opened 2020-10-06 16:50 UTC by maxibello

2020-10-07 13:07 UTC, ios-review requested changes
Легкое задание для вас)

Немного добавим тоже несложных.
Отдельный экран, три кнопки: Deadlock, Race Condition, Priority Inversion.
По нажатию на каждую из этих кнопок должно происходить действие, соответствующее заголовку кнопки.

2020-10-07 13:07 UTC, ios-review commented on s02e05_concurrency/s02e05_concurrency/ImageDownloadVC.swift
> +          [weak self] data, response, error in
response, error не используются.
Можно писать "_" для неиспользуемых параметров.

2020-10-07 13:07 UTC, ios-review commented on s02e05_concurrency/s02e05_concurrency/PrimeNumberVC.swift
> +                if self.isPrime(i).value {
два раза вычисляется?

2020-10-07 13:07 UTC, ios-review commented on s02e05_concurrency/s02e05_concurrency/PrimeNumberVC.swift
> +        let start = CFAbsoluteTimeGetCurrent()
Использование данного времени для определения эффективности по времени может привести к большой ошибке вычислений.
https://developer.apple.com/documentation/corefoundation/1543542-cfabsolutetimegetcurrent

> Repeated calls to this function do not guarantee monotonically increasing results.

Предлагаю вам самостоятельно поискать то время, которое можно использовать для бенчмарков.

2020-10-07 13:07 UTC, ios-review commented on s02e05_concurrency/s02e05_concurrency/PrimeNumberVC.swift
> +                    print(output)
Не знаю....

Может как-то в UI приложения выводить?
Например, добавлять ячейку в таблицу с данным значением.

2020-10-09 11:17 UTC, maxibello commented on s02e05_concurrency/s02e05_concurrency/PrimeNumberVC.swift
> +                if self.isPrime(i).value {
fixed

2020-10-10 15:58 UTC, maxibello commented on s02e05_concurrency/s02e05_concurrency/PrimeNumberVC.swift
> +        let start = CFAbsoluteTimeGetCurrent()
done

2020-10-11 09:06 UTC, ios-review requested changes
По основному заданию все 👌

Поработаете еще с возможными проблемами многопоточности?

2020-10-11 09:06 UTC, ios-review commented on s02e05_concurrency/s02e05_concurrency/ConcurrencyIssuesVC.swift
> +        }    }
Где здесь инверсия приоритетов?

Вот здесь неплохо объясняются два вида инверсии https://ru.coursera.org/lecture/ios-multithreading/priority-inversion-tCmFV

В данном случае наверное можно сказать, что это ограниченная инверсия приоритетов, так как starterQueue ожидает выполнения backgroundQueue, который можно рассматривать как общий ресурс.
Но все таки мне кажется, что здесь нет инверсии как ошибки. Или есть?
Попробуете прокомментировать?

И хочется еще несколько примеров.

2020-10-11 09:06 UTC, ios-review commented on s02e05_concurrency/s02e05_concurrency/PrimeNumberVC.swift
> +        let start = DispatchTime.now().uptimeNanoseconds
👍

2020-10-11 09:06 UTC, ios-review commented on s02e05_concurrency/s02e05_concurrency/ConcurrencyIssuesVC.swift
> +        DispatchQueue.main.sync {}
Более сложный пример покажете?

2020-10-12 07:01 UTC, maxibello commented on s02e05_concurrency/s02e05_concurrency/ConcurrencyIssuesVC.swift
> +        }    }
Здесь идея была в том, что мы повысили приоритет background очереди, вызвав sync. Безусловно это не лучший пример инверсии. Добавил пример неограниченной инверсии.

2020-10-12 07:02 UTC, maxibello commented on s02e05_concurrency/s02e05_concurrency/ConcurrencyIssuesVC.swift
> +        }
изменил код

2020-10-13 12:27 UTC, ios-review approved these changes
nice!

merge

2020-10-13 12:27 UTC, ios-review commented on s02e05_concurrency/s02e05_concurrency/ConcurrencyIssuesVC.swift
> +        }
👍

2020-10-13 12:27 UTC, ios-review commented on s02e05_concurrency/s02e05_concurrency/ConcurrencyIssuesVC.swift
> +    }
Приложение ни разу не упало, но всякий раз выдавало разный результат.

недетерминированный и непредсказуемый результат тоже следствие race condition 👌

2020-10-13 12:27 UTC, ios-review commented on s02e05_concurrency/s02e05_concurrency/ConcurrencyIssuesVC.swift
> +    @IBAction func priorityInversion(_ sender: Any) {
🔥

2020-10-14 13:46 UTC, merged